/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package yakworks.api.problem

import kotlin.test.Test
import kotlin.test.*

//junit but using kotlin classes
class SampleKotlinTest {

    var x = 1

    @Test fun this_is_an_example() {
        assert(1 == x)
    }
}
